models/category.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

class Category extends ActiveRecord
{
    public function getChildren()

    {

        return $this->hasMany(Category::className(), ['parent_id' => 'id']);

    }


    public function getParent()

    {

        return $this->hasOne(Category::className(), ['id' => 'parent_id']);

    }


    public function getUrl()

    {

        return url(['listing/index', 'category' => $this->name, 'id' => $this->id]);

    }
}

controllers/CategoryController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\data\Pagination;
use app\models\Category;
class CategoryController extends Controller
{
    public function actionIndex()
    {
        $categories = $this->get_categories();
        return $this->render('index', [
            'data' => $categories
        ]);
    }


    public function get_categories($parent = 0)
    {
        $html = '<ul>';
        $query = "SELECT * FROM `category` WHERE `parent_id` = '$parent'";
        $categories = Yii::$app->db->createCommand($query)->queryAll();
        foreach($categories as $category)
        {
            $current_id = $category['id'];
            $html .= '<li><input type="button" value="+" id="'.$category['id'].'" class="create_category">' . $category['name'];
            $has_sub = NULL;
            $has_sub = "SELECT COUNT(`parent_id`) FROM `category` WHERE `parent_id` = '$current_id'";
            $has_sub = Yii::$app->db->createCommand($has_sub)->queryAll();
            if(is_array($has_sub))
            {
                $html .= $this->get_categories($current_id);
            }
            $html .= '</li>';
        }
        $html .= '</ul>';
        return $html;
    }

    
    public function actionAjax()
    {
        $parent_id = Yii::$app->request->post('parent_id');
        $category = new Category();
        $category->parent_id = $parent_id;
        $category_parent = Category::find()->where(['id'=>$parent_id])->one();
        if($category_parent->parent_id != 0){
            $count = Category::find()->where(['parent_id' => $parent_id])->count();
            preg_match_all('!\d+!', $category_parent->name , $matches);
            $count+= 1;
            if(is_array($matches))
                $category->name = 'SUB '.$category_parent->name.'-'.$count;
            else
            $category->name = 'SUB '.$category_parent->name.'1';

         } else{
            //die('in');
            $count = Category::find()->where(['parent_id' => $parent_id])->count();
            $count+= 1;
            $category->name = 'SUB '.$category_parent->name.$count;
         }
            
        $category->save();
    }


}

views/category/index.php
<h1>Categories</h1>
<div>
<?= $data ?>
</div>
<style>
    input{
        margin:5px;
    }
</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
        $(document).ready(function () {
            $(".create_category").on('click',function () {
                sendFirstCategory($(this).attr('id'));
            });
        });

    function sendFirstCategory($parent_id) {
        var test = "this is an ajax test";
        $.ajax({
            type: "POST",
            url: "<?php echo Yii::$app->getUrlManager()->createUrl('category/ajax')  ; ?>",
            data: {parent_id: $parent_id},
            success: function (test) {
                window.location.href = '<?php echo Yii::$app->getUrlManager()->createUrl('category/')  ; ?>'
            },
            error: function (exception) {
                alert(exception);
            }
        })
        ;
    }
</script>